### ISSUE TITLE
Menu Dropdown Auto Select First Item

### ISSUE THREAD

**Issue by curateship** [CodyHouse/cd-interactive-table-changelog#2]
Hello, this is the continuation of this issue here:
https://github.com/CodyHouse/codyhouse-framework/discussions/118

I have already looked at the menu component. While I can remove the hover class. It just remove that styling altogether.

I just wanted so that it doesn't auto select the first item. How would I be able to do this?

**Comment by claudia-romano** [comment]
Hi there, you should modify is the focus effect, not the hover effect.
 
If you do not want the first item to be focused when the menu is open, then you can modify the JS code - remove line 60:
```
Util.moveFocus(this.menuItems[0]); // remove this line of code
```
I would discourage this as this would reduce usability when using the keyboard (without mouse/touch).
